[tool.poetry]
name = "3detr"
version = "0.1.0"
description = ""
authors = ["wojiazaiyugang <wojiazaiyugang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
matplotlib = "^3.6.3"
opencv-python = "^4.7.0.68"
plyfile = "^0.7.4"
networkx = ">=2.2,<2.3"
numpy = "<1.24"
cython = "^0.29.33"
tensorboardx = "^2.5.1"
tensorboard = "1.11"
algorithm-assistant = {url = "http://192.168.0.21:10086/simple/AlgorithmAssistant/algorithm_assistant-1.0.12-py3-none-any.whl"}
torch = {version = "2.0.1", source = "pytorch"}

[[tool.poetry.source]]
name = "ustc"
url = "https://pypi.mirrors.ustc.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
